### ISSUE TITLE
Case design

### ISSUE THREAD

**Issue by OwendB1** [FHICT-Owen/CTF-U13#17]

**Comment by i408770** [comment]
Case has been designed and interated upon once. 

<div>
<img src="https://user-images.githubusercontent.com/62698897/171615585-c4c6a9b1-d5e5-43b5-bbce-fd292179c4d0.jpg" width="325" height="325">
<img src="https://user-images.githubusercontent.com/62698897/171614367-c9cfb753-72a6-4c89-8cdb-bf9a3f58bcde.PNG" width="325" height="325">
</div>
